pipeline {
    agent any

    parameters {
        string(name: 'REPOSITORY', defaultValue: '', description: 'Bitbucket repository slug')
        string(name: 'BRANCH', defaultValue: 'main', description: 'Branch generated by ReplayLab')
        string(name: 'CASE_ID', defaultValue: '', description: 'ReplayLab case id')
        booleanParam(name: 'RUN_INTEGRATION_TESTS', defaultValue: true, description: 'Run integration tests')
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checkout must be connected to the Etiya Bitbucket credential and repository."
                checkout scm
            }
        }

        stage('Build and Unit Tests') {
            steps {
                sh 'mvn -B clean test'
            }
        }

        stage('Integration Tests') {
            when {
                expression { return params.RUN_INTEGRATION_TESTS }
            }
            steps {
                sh 'mvn -B verify -DskipUnitTests'
            }
        }

        stage('Publish Results') {
            steps {
                junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml,**/target/failsafe-reports/*.xml'
                archiveArtifacts allowEmptyArchive: true, artifacts: '**/target/*.jar,**/target/site/**'
            }
        }
    }

    post {
        always {
            echo "ReplayLab case: ${params.CASE_ID}"
        }
    }
}
