package com.etiya.replaylab.domain;

public enum NotificationType {
    WORKFLOW_SUCCESS,
    WORKFLOW_PARTIAL_SUCCESS,
    WORKFLOW_FAILED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    JIRA_COMMENT_PUBLISHED,
    RETRY_REQUIRED,
    INTEGRATION_UNAVAILABLE,
    AI_ANALYSIS_COMPLETED,
    AI_ANALYSIS_FAILED,
    AI_PROVIDER_UNAVAILABLE
}
