package com.etiya.replayfix.domain;

public enum EvidenceType {
    JIRA_ISSUE,
    LOKI_QUERY_PLAN,
    LOKI_LOG,
    LOKI_CORRELATION_SIGNALS,
    LOKI_SECOND_PASS,
    INCIDENT_TIMELINE,
    TEMPO_ENRICHMENT,
    DETERMINISTIC_ROOT_CAUSE,
    REPOSITORY_RESOLUTION,
    SOURCE_CHECKOUT,
    INCIDENT_VERSION,
    JENKINS_BUILD_CONTEXT,
    SOURCE_CONTEXT,
    AI_INPUT_BUNDLE,
    AI_ROOT_CAUSE,
    TEMPO_TRACE,
    CONFLUENCE_PAGE,
    REPLAY_OUTPUT,
    GENERATED_TEST,
    GENERATED_PATCH,
    JENKINS_RESULT,
    PULL_REQUEST
}
