package com.etiya.replayfix.domain;

public enum NotificationType {
    WORKFLOW_SUCCESS,
    WORKFLOW_PARTIAL_SUCCESS,
    WORKFLOW_FAILED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    JIRA_COMMENT_PUBLISHED,
    RETRY_REQUIRED,
    INTEGRATION_UNAVAILABLE
}
