package com.etiya.replayfix.domain;

public enum ReplayCaseStatus {
    NEW,
    CONTEXT_COLLECTING,
    CONTEXT_READY,
    ENVIRONMENT_PROVISIONING,
    ENVIRONMENT_READY,
    REPLAYING,
    REPRODUCED,
    REPRODUCTION_FAILED,
    TEST_GENERATING,
    TEST_GENERATED,
    PATCH_GENERATING,
    PATCH_GENERATED,
    VALIDATING,
    VALIDATION_FAILED,
    VALIDATED,
    PR_CREATED,
    AWAITING_HUMAN_REVIEW,
    COMPLETED,
    INSUFFICIENT_EVIDENCE,
    POLICY_BLOCKED,
    FAILED
}
