package com.etiya.replayfix.model;

public enum LocalTestExecutionStatus {
    DEFECT_REPRODUCED,
    TEST_PASSED_UNEXPECTED_BEFORE_FIX,
    SCAFFOLD_FAILURE_NOT_REPRODUCED,
    COMPILE_FAILURE,
    TEST_NOT_FOUND,
    TEST_FAILURE_UNCLASSIFIED,
    TIMEOUT,
    INFRASTRUCTURE_FAILURE
}
